name: alloy_annotations
description: Annotations for Alloy — @AlloyInject, @injected, @AlloyBootstrap, @AlloyInit and @AlloyScopeRoot.
version: 0.1.0
repository: https://github.com/rutikeyone/alloy
issue_tracker: https://github.com/rutikeyone/alloy/issues
topics:
  - dependency-injection
  - annotations
  - codegen
  - di

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  meta: ^1.16.0
