builders:
  alloy_property_injection:
    import: "package:alloy_generator/builder.dart"
    builder_factories: ["alloyPropertyInjectionBuilder"]
    build_extensions: { ".dart": [".alloy.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      generate_for:
        - lib/**
  alloy_scan:
    import: "package:alloy_generator/builder.dart"
    builder_factories: ["alloyScanBuilder"]
    build_extensions: { ".dart": [".alloy.json"] }
    auto_apply: dependents
    build_to: cache
    runs_before: ["alloy_generator|alloy_container"]
    defaults:
      generate_for:
        - lib/**
  alloy_container:
    import: "package:alloy_generator/builder.dart"
    builder_factories: ["alloyContainerBuilder"]
    build_extensions: { "$lib$": ["alloy.g.dart"] }
    auto_apply: dependents
    build_to: source
